-dontobfuscate
-dontoptimize
-keep class com.mykerd.synchrogaea.** { *; }
-keepattributes SourceFile,LineNumberTable
-keepparameternames
-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep class kotlin.Metadata { *; }